CREATE TABLE IF NOT EXISTS ${database}.${prefix}cookbook (
  id BINARY(16) NOT NULL,
  parent BINARY(16),
  description VARCHAR(255) NOT NULL,
  creation_time TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
    NOT NULL,
  last_update TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
    NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (parent) REFERENCES ${prefix}cookbook (id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
)Engine=InnoDB;
